# build.ps1 - Generates install.ps1 from installer/ folder + source files
#
# Placeholders:
#   {{VERSION}}         - replaced with version from updates/latest.json
#   {{FILE:path}}       - replaced with the contents of the file at that path
#   {{INCLUDE:path}}    - replaced with the processed contents of another template file
#                         (path is relative to the project root)
#
# Usage:  .\build.ps1

param(
    [string]$Template = 'installer\main.ps1',
    [string]$Output = 'install.ps1'
)

$ErrorActionPreference = 'Stop'
$root = Split-Path $MyInvocation.MyCommand.Path -Parent

$latestPath = Join-Path $root 'updates\latest.json'
if (Test-Path $latestPath) {
    $latest  = Get-Content $latestPath -Raw | ConvertFrom-Json
    $Version = $latest.version
} else {
    Write-Error "updates/latest.json not found."
    exit 1
}

$buildStart = [System.Diagnostics.Stopwatch]::StartNew()
Write-Host "Building install.ps1  (v$Version)" -ForegroundColor Cyan

$outputPath = Join-Path $root $Output

# Recursively process a template file, resolving {{INCLUDE:}}, {{FILE:}}, and {{VERSION}}
function Resolve-Template {
    param([string]$FilePath)

    if (-not (Test-Path $FilePath)) {
        Write-Error "Template not found: $FilePath"
        exit 1
    }

    $lines  = Get-Content $FilePath -Encoding UTF8
    $result = [System.Collections.Generic.List[string]]::new()

    foreach ($line in $lines) {
        # {{INCLUDE:path}} - recursively include and process another template file
        if ($line -match '^\{\{INCLUDE:(.+?)\}\}$') {
            $incPath = Join-Path $root $Matches[1]
            $included = Resolve-Template $incPath
            foreach ($incLine in $included) { $result.Add($incLine) }
            continue
        }

        # {{EMBED_DIR:path}} - embed every file under a directory as $FILE_xxx variables
        # Variable name: FILE_ + relative path with /, \, ., - replaced by _ and uppercased
        # e.g. src/data/app.py -> $FILE_DATA_APP_PY
        if ($line -match '^\{\{EMBED_DIR:(.+?)\}\}$') {
            $dirPath = Join-Path $root $Matches[1]
            $result.Add("# --- Embedded file contents (auto-generated by build.ps1) ---")
            Get-ChildItem $dirPath -Recurse -File | Sort-Object FullName | ForEach-Object {
                $rel     = $_.FullName.Substring($dirPath.Length).TrimStart('\','/')
                $varName = 'FILE_' + ($rel -replace '[/\\\.\-]', '_').ToUpper()
                $content = (Get-Content $_.FullName -Raw -Encoding UTF8).TrimEnd("`r`n")
                $result.Add("`$$varName = @'")
                $result.Add($content)
                $result.Add("'@")
                $result.Add("")
            }
            continue
        }

        # {{VERSION}} replacement (can appear anywhere on a line)
        if ($line -match '\{\{VERSION\}\}') {
            $line = $line -replace '\{\{VERSION\}\}', $Version
        }

        # {{FILE:path}} - must be the only content on the line (inside a here-string)
        if ($line -match '^\{\{FILE:(.+?)\}\}$') {
            $filePath = Join-Path $root $Matches[1]
            if (-not (Test-Path $filePath)) {
                Write-Warning "Source file not found: $filePath - leaving placeholder"
                $result.Add($line)
                continue
            }
            $content = (Get-Content $filePath -Raw -Encoding UTF8).TrimEnd("`r`n")
            $result.Add($content)
            continue
        }

        $result.Add($line)
    }

    return $result
}

$templatePath = Join-Path $root $Template
$result = Resolve-Template $templatePath

$outputText = $result -join "`r`n"
[System.IO.File]::WriteAllText($outputPath, $outputText, (New-Object System.Text.UTF8Encoding($false)))

$lineCount = $result.Count
$sizeKB    = [math]::Round((Get-Item $outputPath).Length / 1024, 1)
$elapsed   = [math]::Round($buildStart.Elapsed.TotalSeconds, 2)
Write-Host "OK  $outputPath -- $lineCount lines, $sizeKB KB  ($($elapsed)s)" -ForegroundColor Green
