{{INCLUDE:installer/bootstrap.ps1}}
{{INCLUDE:installer/ui/icon.ps1}}
{{INCLUDE:installer/utils/controls.ps1}}
{{EMBED_DIR:src}}
{{INCLUDE:installer/utils/utils.ps1}}
{{INCLUDE:installer/config/colors.ps1}}
{{INCLUDE:installer/ui/factories.ps1}}
{{INCLUDE:installer/ui/form.ps1}}
{{INCLUDE:installer/pages/00-welcome.ps1}}
{{INCLUDE:installer/pages/01-license.ps1}}
{{INCLUDE:installer/pages/02-deps.ps1}}
{{INCLUDE:installer/pages/03-location.ps1}}
{{INCLUDE:installer/pages/04-confirm.ps1}}
{{INCLUDE:installer/pages/05-install.ps1}}
{{INCLUDE:installer/pages/06-done.ps1}}
{{INCLUDE:installer/pages/07-reinstall.ps1}}
{{INCLUDE:installer/pages/08-update.ps1}}
{{INCLUDE:installer/config/state.ps1}}
{{INCLUDE:installer/core/install-helpers.ps1}}
{{INCLUDE:installer/core/install-steps.ps1}}
{{INCLUDE:installer/core/navigation.ps1}}
{{INCLUDE:installer/core/handlers.ps1}}
{{INCLUDE:installer/run.ps1}}
